#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 25 18:28:31 2019

@author: amir
"""

from tensorflow.python.client import device_lib

device_lib.list_local_devices()
import tensorflow as tf
tf.__version__
tf.test.is_gpu_available()
tf.test.gpu_device_name()


import subprocess

n = str(subprocess.check_output(["nvidia-smi", "-L"])).count('UUID')

n

sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))


import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))
    
    
with tf.Session() as sess:
  devices = sess.list_devices()
  print(devices)
  
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


import tensorflow as tf
if tf.test.gpu_device_name():
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
else:
    print("Please install GPU version of TF")
    
    
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
